# Generated by Django 5.0.3 on 2024-03-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='file_upload',
            field=models.FileField(upload_to='static/media'),
        ),
    ]
