# Generated by Django 5.0.3 on 2024-03-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='file_upload',
            field=models.FileField(upload_to='media/music/'),
        ),
    ]
